### ISSUE TITLE
这个版本需要安装php7么，不兼容5.6的么

### ISSUE THREAD

**Issue by Martin0709** [lanceWan/any#3]
λ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
  Problem 2
    - Installation request for vinkla/hashids 3.1.0 -> satisfiable by vinkla/hashids[3.1.0].
    - vinkla/hashids 3.1.0 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
  Problem 3
    - Installation request for yajra/laravel-datatables-buttons v2.0.3 -> satisfiable by yajra/laravel-datatables-buttons[v2.0.3].
    - yajra/laravel-datatables-buttons v2.0.3 requires php >=7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
  Problem 4
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
    - laravel/framework v5.4.30 requires doctrine/inflector ~1.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - Installation request for laravel/framework v5.4.30 -> satisfiable by laravel/framework[v5.4.30].

**Comment by lanceWan** [comment]
我安装的扩展好像要求7.0版本的
