### ISSUE TITLE
No hint path defined for [flash]

### ISSUE THREAD

**Issue by yujiak** [lanceWan/any#7]
@include('flash::message')   一开始没啥问题的，今天突然就报这句错误
ErrorException (E_ERROR)
No hint path defined for [flash]. (View: F:\any-master\resources\views\themes\admin\inspinia\menu\list.blade.php)

**Comment by lanceWan** [comment]
@yujiak laracasts/flash 的版本告诉我一下。还有你下载的是那个分支的代码

**Comment by lanceWan** [comment]
安装一下 Laracast/flash 就好了
